# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'numlock_win.ui'
#
# Created: Wed Jan 22 19:20:46 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1060, 910)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        MainWindow.setFont(font)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButton_9 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(880, 830, 101, 41))
        self.pushButton_9.setMinimumSize(QtCore.QSize(101, 41))
        self.pushButton_9.setMaximumSize(QtCore.QSize(101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(50, 19, 971, 341))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(640, 90, 311, 121))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.radioButton = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton.setGeometry(QtCore.QRect(30, 30, 102, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 60, 102, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.label_25 = QtGui.QLabel(self.groupBox_4)
        self.label_25.setGeometry(QtCore.QRect(40, 90, 61, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.comboBox = QtGui.QComboBox(self.groupBox_4)
        self.comboBox.setGeometry(QtCore.QRect(96, 86, 51, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_2.setGeometry(QtCore.QRect(110, 30, 87, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_3.setGeometry(QtCore.QRect(110, 60, 111, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_7 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_7.setGeometry(QtCore.QRect(220, 30, 87, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.checkBox_8 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_8.setGeometry(QtCore.QRect(220, 60, 111, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(350, 0, 511, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 91, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(240, 30, 21, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(240, 60, 21, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(290, 30, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(290, 60, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(440, 30, 41, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lE_srate = QtGui.QLineEdit(self.groupBox_2)
        self.lE_srate.setGeometry(QtCore.QRect(130, 30, 101, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.lE_srate.setFont(font)
        self.lE_srate.setObjectName(_fromUtf8("lE_srate"))
        self.lE_PUarea = QtGui.QLineEdit(self.groupBox_2)
        self.lE_PUarea.setGeometry(QtCore.QRect(130, 60, 101, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.lE_PUarea.setFont(font)
        self.lE_PUarea.setObjectName(_fromUtf8("lE_PUarea"))
        self.lE_current = QtGui.QLineEdit(self.groupBox_2)
        self.lE_current.setGeometry(QtCore.QRect(360, 30, 71, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.lE_current.setFont(font)
        self.lE_current.setObjectName(_fromUtf8("lE_current"))
        self.lE_gain = QtGui.QLineEdit(self.groupBox_2)
        self.lE_gain.setGeometry(QtCore.QRect(360, 60, 71, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.lE_gain.setFont(font)
        self.lE_gain.setObjectName(_fromUtf8("lE_gain"))
        self.checkBox_4 = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_4.setGeometry(QtCore.QRect(450, 60, 51, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 90, 621, 121))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(260, 30, 21, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(30, 30, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(260, 60, 21, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(30, 60, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(570, 30, 21, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(340, 30, 101, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(570, 60, 21, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(340, 60, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox.setGeometry(QtCore.QRect(30, 90, 133, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit.setGeometry(QtCore.QRect(150, 30, 101, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 60, 101, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(460, 60, 101, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(460, 30, 101, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_10 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_10.setGeometry(QtCore.QRect(170, 90, 81, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.checkBox_6 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_6.setGeometry(QtCore.QRect(340, 90, 141, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 210, 941, 101))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.pushButton_7 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_7.setGeometry(QtCore.QRect(28, 24, 95, 33))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_6.setGeometry(QtCore.QRect(140, 62, 95, 33))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_8 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_8.setGeometry(QtCore.QRect(812, 60, 95, 33))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.lineEdit_13 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_13.setGeometry(QtCore.QRect(820, 32, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.label_19 = QtGui.QLabel(self.groupBox_5)
        self.label_19.setGeometry(QtCore.QRect(750, 32, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.groupBox_5)
        self.label_20.setGeometry(QtCore.QRect(130, 32, 101, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.groupBox_5)
        self.label_21.setGeometry(QtCore.QRect(250, 70, 101, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.groupBox_5)
        self.label_22.setGeometry(QtCore.QRect(350, 70, 101, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.groupBox_5)
        self.label_23.setGeometry(QtCore.QRect(230, 32, 491, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.groupBox_5)
        self.label_24.setGeometry(QtCore.QRect(470, 70, 321, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setText(_fromUtf8(""))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.checkBox_5 = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_5.setGeometry(QtCore.QRect(40, 68, 111, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 331, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(180, 60, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 30, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.lE_ncol = QtGui.QLineEdit(self.groupBox)
        self.lE_ncol.setGeometry(QtCore.QRect(110, 30, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.lE_ncol.setFont(font)
        self.lE_ncol.setObjectName(_fromUtf8("lE_ncol"))
        self.lE_dBdtcol = QtGui.QLineEdit(self.groupBox)
        self.lE_dBdtcol.setGeometry(QtCore.QRect(110, 60, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.lE_dBdtcol.setFont(font)
        self.lE_dBdtcol.setObjectName(_fromUtf8("lE_dBdtcol"))
        self.lE_refcol = QtGui.QLineEdit(self.groupBox)
        self.lE_refcol.setGeometry(QtCore.QRect(260, 60, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.lE_refcol.setFont(font)
        self.lE_refcol.setObjectName(_fromUtf8("lE_refcol"))
        self.label_26 = QtGui.QLabel(self.groupBox)
        self.label_26.setGeometry(QtCore.QRect(180, 30, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.lE_datcol = QtGui.QLineEdit(self.groupBox)
        self.lE_datcol.setGeometry(QtCore.QRect(260, 30, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.lE_datcol.setFont(font)
        self.lE_datcol.setObjectName(_fromUtf8("lE_datcol"))
        self.pushButton_5 = QtGui.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(866, 20, 95, 33))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_4 = QtGui.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(866, 54, 95, 33))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.lineEdit_16 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_16.setGeometry(QtCore.QRect(140, 60, 113, 22))
        self.lineEdit_16.setText(_fromUtf8(""))
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.label_27 = QtGui.QLabel(self.tab_3)
        self.label_27.setGeometry(QtCore.QRect(50, 20, 81, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.tab_3)
        self.label_28.setGeometry(QtCore.QRect(50, 60, 81, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.tab_3)
        self.label_29.setGeometry(QtCore.QRect(260, 60, 81, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.comboBox_2 = QtGui.QComboBox(self.tab_3)
        self.comboBox_2.setGeometry(QtCore.QRect(140, 20, 121, 26))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.lineEdit_17 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_17.setGeometry(QtCore.QRect(550, 30, 113, 22))
        self.lineEdit_17.setText(_fromUtf8(""))
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.label_30 = QtGui.QLabel(self.tab_3)
        self.label_30.setGeometry(QtCore.QRect(670, 30, 31, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.tab_3)
        self.label_31.setGeometry(QtCore.QRect(400, 30, 151, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.lineEdit_18 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_18.setGeometry(QtCore.QRect(550, 60, 113, 22))
        self.lineEdit_18.setText(_fromUtf8(""))
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.label_33 = QtGui.QLabel(self.tab_3)
        self.label_33.setGeometry(QtCore.QRect(400, 60, 151, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_32 = QtGui.QLabel(self.tab_3)
        self.label_32.setGeometry(QtCore.QRect(670, 60, 31, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_34 = QtGui.QLabel(self.tab_3)
        self.label_34.setGeometry(QtCore.QRect(400, 90, 151, 16))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.lineEdit_19 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_19.setGeometry(QtCore.QRect(550, 90, 113, 22))
        self.lineEdit_19.setText(_fromUtf8(""))
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.label_35 = QtGui.QLabel(self.tab_3)
        self.label_35.setGeometry(QtCore.QRect(670, 90, 61, 16))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_36 = QtGui.QLabel(self.tab_3)
        self.label_36.setGeometry(QtCore.QRect(110, 200, 771, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.comboBox_3 = QtGui.QComboBox(self.tab_3)
        self.comboBox_3.setGeometry(QtCore.QRect(140, 110, 121, 26))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.label_37 = QtGui.QLabel(self.tab_3)
        self.label_37.setGeometry(QtCore.QRect(50, 110, 81, 16))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_38 = QtGui.QLabel(self.tab_3)
        self.label_38.setGeometry(QtCore.QRect(400, 160, 151, 16))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.lineEdit_20 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_20.setGeometry(QtCore.QRect(550, 160, 113, 22))
        self.lineEdit_20.setText(_fromUtf8(""))
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.label_39 = QtGui.QLabel(self.tab_3)
        self.label_39.setGeometry(QtCore.QRect(50, 160, 111, 16))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.lineEdit_21 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_21.setGeometry(QtCore.QRect(164, 158, 93, 22))
        self.lineEdit_21.setText(_fromUtf8(""))
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tab_2)
        self.plainTextEdit.setEnabled(True)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 0, 941, 321))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tabWidget_2 = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(50, 370, 981, 457))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        font.setPointSize(10)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setTabPosition(QtGui.QTabWidget.East)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.qwtPlot = Qwt5.QwtPlot(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlot.sizePolicy().hasHeightForWidth())
        self.qwtPlot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.qwtPlot.setFont(font)
        self.qwtPlot.setObjectName(_fromUtf8("qwtPlot"))
        self.horizontalLayout.addWidget(self.qwtPlot)
        self.qwtPlot_2 = Qwt5.QwtPlot(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlot_2.sizePolicy().hasHeightForWidth())
        self.qwtPlot_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.qwtPlot_2.setFont(font)
        self.qwtPlot_2.setObjectName(_fromUtf8("qwtPlot_2"))
        self.horizontalLayout.addWidget(self.qwtPlot_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.layoutWidget = QtGui.QWidget(self.tab_5)
        self.layoutWidget.setGeometry(QtCore.QRect(6, 10, 945, 431))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.qwtPlot_3 = Qwt5.QwtPlot(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        self.qwtPlot_3.setFont(font)
        self.qwtPlot_3.setObjectName(_fromUtf8("qwtPlot_3"))
        self.horizontalLayout_2.addWidget(self.qwtPlot_3)
        self.qwtPlot_4 = Qwt5.QwtPlot(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times"))
        self.qwtPlot_4.setFont(font)
        self.qwtPlot_4.setObjectName(_fromUtf8("qwtPlot_4"))
        self.horizontalLayout_2.addWidget(self.qwtPlot_4)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.label_40 = QtGui.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(60, 846, 81, 16))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1060, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOuvrir = QtGui.QAction(MainWindow)
        self.actionOuvrir.setObjectName(_fromUtf8("actionOuvrir"))
        self.actionSauver = QtGui.QAction(MainWindow)
        self.actionSauver.setObjectName(_fromUtf8("actionSauver"))
        self.actionQuitter = QtGui.QAction(MainWindow)
        self.actionQuitter.setObjectName(_fromUtf8("actionQuitter"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lE_ncol, self.lE_datcol)
        MainWindow.setTabOrder(self.lE_datcol, self.lE_dBdtcol)
        MainWindow.setTabOrder(self.lE_dBdtcol, self.lE_refcol)
        MainWindow.setTabOrder(self.lE_refcol, self.lE_srate)
        MainWindow.setTabOrder(self.lE_srate, self.lE_current)
        MainWindow.setTabOrder(self.lE_current, self.lE_PUarea)
        MainWindow.setTabOrder(self.lE_PUarea, self.lE_gain)
        MainWindow.setTabOrder(self.lE_gain, self.checkBox_4)
        MainWindow.setTabOrder(self.checkBox_4, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.lineEdit_4)
        MainWindow.setTabOrder(self.lineEdit_4, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.checkBox)
        MainWindow.setTabOrder(self.checkBox, self.lineEdit_10)
        MainWindow.setTabOrder(self.lineEdit_10, self.checkBox_6)
        MainWindow.setTabOrder(self.checkBox_6, self.radioButton)
        MainWindow.setTabOrder(self.radioButton, self.radioButton_2)
        MainWindow.setTabOrder(self.radioButton_2, self.checkBox_2)
        MainWindow.setTabOrder(self.checkBox_2, self.checkBox_3)
        MainWindow.setTabOrder(self.checkBox_3, self.checkBox_7)
        MainWindow.setTabOrder(self.checkBox_7, self.checkBox_8)
        MainWindow.setTabOrder(self.checkBox_8, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.pushButton_7)
        MainWindow.setTabOrder(self.pushButton_7, self.checkBox_5)
        MainWindow.setTabOrder(self.checkBox_5, self.pushButton_6)
        MainWindow.setTabOrder(self.pushButton_6, self.lineEdit_13)
        MainWindow.setTabOrder(self.lineEdit_13, self.pushButton_8)
        MainWindow.setTabOrder(self.pushButton_8, self.pushButton_9)
        MainWindow.setTabOrder(self.pushButton_9, self.lineEdit_16)
        MainWindow.setTabOrder(self.lineEdit_16, self.comboBox_2)
        MainWindow.setTabOrder(self.comboBox_2, self.lineEdit_17)
        MainWindow.setTabOrder(self.lineEdit_17, self.lineEdit_18)
        MainWindow.setTabOrder(self.lineEdit_18, self.lineEdit_19)
        MainWindow.setTabOrder(self.lineEdit_19, self.comboBox_3)
        MainWindow.setTabOrder(self.comboBox_3, self.lineEdit_20)
        MainWindow.setTabOrder(self.lineEdit_20, self.plainTextEdit)
        MainWindow.setTabOrder(self.plainTextEdit, self.tabWidget_2)
        MainWindow.setTabOrder(self.tabWidget_2, self.tabWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Linx", None))
        self.pushButton_9.setText(_translate("MainWindow", "Exit", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Plot Options", None))
        self.radioButton.setText(_translate("MainWindow", "R(B)", None))
        self.radioButton_2.setText(_translate("MainWindow", "R(t)", None))
        self.label_25.setText(_translate("MainWindow", "Sample :", None))
        self.checkBox_2.setText(_translate("MainWindow", "In phase", None))
        self.checkBox_3.setText(_translate("MainWindow", "Out of phase", None))
        self.checkBox_7.setText(_translate("MainWindow", "Up", None))
        self.checkBox_8.setText(_translate("MainWindow", "Down", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Experimental Settings", None))
        self.label_4.setText(_translate("MainWindow", "Sample Rate :", None))
        self.label_7.setText(_translate("MainWindow", "Hz", None))
        self.label_6.setText(_translate("MainWindow", "m2", None))
        self.label_5.setText(_translate("MainWindow", "Pickup Coil Area :", None))
        self.label_8.setText(_translate("MainWindow", "Intensity :", None))
        self.label_9.setText(_translate("MainWindow", "Gain :", None))
        self.label_10.setText(_translate("MainWindow", "mA", None))
        self.checkBox_4.setText(_translate("MainWindow", "RMS", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Analysis Parameters", None))
        self.label_11.setText(_translate("MainWindow", "Hz", None))
        self.label_12.setText(_translate("MainWindow", "Lowpass Cutoff :", None))
        self.label_13.setText(_translate("MainWindow", "Hz", None))
        self.label_14.setText(_translate("MainWindow", "Modulation Rate :", None))
        self.label_15.setText(_translate("MainWindow", "ms", None))
        self.label_16.setText(_translate("MainWindow", "Time Constant :", None))
        self.label_17.setText(_translate("MainWindow", "°", None))
        self.label_18.setText(_translate("MainWindow", "Manual Phase :", None))
        self.checkBox.setText(_translate("MainWindow", "Spikes Eraser     x", None))
        self.checkBox_6.setText(_translate("MainWindow", "dB/dt subtraction", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Load & Save", None))
        self.pushButton_7.setText(_translate("MainWindow", "Load Data", None))
        self.pushButton_6.setText(_translate("MainWindow", "Batch", None))
        self.pushButton_8.setText(_translate("MainWindow", "Save Data", None))
        self.label_19.setText(_translate("MainWindow", "Thin out :", None))
        self.label_20.setText(_translate("MainWindow", "File Opened :", None))
        self.label_21.setText(_translate("MainWindow", "Files Treated :", None))
        self.label_22.setText(_translate("MainWindow", "--", None))
        self.label_23.setText(_translate("MainWindow", "none", None))
        self.checkBox_5.setText(_translate("MainWindow", "Binary File", None))
        self.groupBox.setTitle(_translate("MainWindow", "Raw File Options", None))
        self.label_3.setText(_translate("MainWindow", "Ref. col. n°", None))
        self.label_2.setText(_translate("MainWindow", "dB/dt col. n°", None))
        self.label.setText(_translate("MainWindow", "Column # :", None))
        self.label_26.setText(_translate("MainWindow", "Data. col. n°", None))
        self.pushButton_5.setText(_translate("MainWindow", "Load Config", None))
        self.pushButton_4.setText(_translate("MainWindow", "Save Config", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Configuration", None))
        self.label_27.setText(_translate("MainWindow", "Filter Type :", None))
        self.label_28.setText(_translate("MainWindow", "Filter order :", None))
        self.label_29.setText(_translate("MainWindow", "\"n\" or \"auto\" ", None))
        self.label_30.setText(_translate("MainWindow", "dB", None))
        self.label_31.setText(_translate("MainWindow", "Passband attenuation :", None))
        self.label_33.setText(_translate("MainWindow", "Stopband attenuation :", None))
        self.label_32.setText(_translate("MainWindow", "dB", None))
        self.label_34.setText(_translate("MainWindow", "Stopband frequency :", None))
        self.label_35.setText(_translate("MainWindow", "x Cutoff", None))
        self.label_36.setText(_translate("MainWindow", "Messing with these parameters may produce meaningless results", None))
        self.label_37.setText(_translate("MainWindow", "Signal Type :", None))
        self.label_38.setText(_translate("MainWindow", "dbdt highpass cutoff :", None))
        self.label_39.setText(_translate("MainWindow", "Phase accuracy :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Advanced Options", None))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Aide à l\'utilisation du lock-in numérique :\n"
"\n"
"1) Raw Configuration : contient toute les données concernant le formatage du fichier de données brut.\n"
"    i) Nombre de colonnes (en général 2*nombre d\'échantillon +1)\n"
"    ii) Colonne contenant le dbdt (en général colonne 1)\n"
"    iii) Colonne(s) de référence : plusieurs colonnes peuvent être indiquées séparées par une \",\" (ex : 2,3)\n"
"    iv) Colonnes contenant la mesure échantillon. Les colonnes sont une fois de plus séparées par une \",\".\n"
"\n"
"Dans le cas où une seule colonne de référence est indiquée, cette colonne est utilisée pour chaque échantillon. Dans le cas de plusieurs colonnes de référence, elles sont associées directement avec les colonnes de données correspondantes. Le nombre de colonne de référence doit dans ce cas être identique au nombre de colonnes de données (quitte a répéter la même colonne de référence plusieurs fois colref = \"1,2,2\" coldata=\"3,4,5\")\n"
"\n"
"2) Experimental Settings : contient tous les paramètres expérimentaux.\n"
"    i) Sample rate : fréquence d\'échantillonage de la carte d\'acquisition\n"
"    ii) PU Area : surface de la pickup en m2\n"
"    iii) Intensity : intensité du courant émis par le lockin en mA\n"
"    iv) Gain : le gain :)\n"
"\n"
"Deux boutons permettant de sauvegarder ou de charger les fichier de configuration sont disponibles. Ils permettent de sauver et de restaurer l\'état de tous les champs éditables.\n"
"\n"
"3) Analysis Parameters : contient tous les paramètres concernant le traitement des données.\n"
"    i) Lowpass Cutoff : fréquence de coupure du filtre passe-bas. Cette fréquence définie directement le champ \"Time Constant\". Une modification du champ \"Time Constant\" modifie également le champ \"Lowpass Cutoff\"\n"
"    ii) Modulation Rate : champ non éditable contenant la fréquence du signale de référence (fréquence de modulation du lock-in)\n"
"    iii) Par défaut le calcul cherche à obtenir un signal hors-phase minimum et un signal en pahse maximum. Il est toutefois possible d\'ajouter un déphasage manuel afin d\'inverser les deux canaux par exemple.\n"
"    iv) Spikes Eraser : une fois cochée, le signal brut est retraité afin de tenir compte des \"spikes\". Une analyse de la dérivée du signal brut est effectuée afin de supprimer les anomalies. Le signal est ensuite intégré et retraité. Décocher la case réaffiche le signal d\'origine.\n"
"\n"
"4) Plot options : choix de l\'affichage R(B) ou R(t) et choix de l\'échantillon a afficher. L\'échantillon 1 correspond à la première colonne de données, etc ...\n"
"\n"
"5) Load and Save : chargement des fichiers a analyser et sauvegarde des données traitées.\n"
"    i) Load Data : charge un fichier binaire unique et le traite en fonction des champs remplis dans les parties précédentes.\n"
"    ii) Save Data : sauvegarde les données traitées dans un fichier choisi par l\'utilisateur. Le champ Thin-out associé permet de réduire le nombre de points sauvegardé.\n"
"    iii) Batch : permet de traiter une série de fichiers à la chaine sans affichage. Les fichiers sont sauvegardés dans des fichiers texte : \"input_out.txt\" avec input le nom du fichier brut. Seule l\'analyse des spikes n\'est pas prise en compte dans ce cas.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Help", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Signal", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Field", None))
        self.label_40.setText(_translate("MainWindow", "Version: 1.0", None))
        self.actionOuvrir.setText(_translate("MainWindow", "Ouvrir ...", None))
        self.actionSauver.setText(_translate("MainWindow", "Sauver ...", None))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter", None))

from PyQt4 import Qwt5
